backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:

  - name: "languages"
    label: "Languages"
    folder: "data/translations"
    create: true
    extension: json
    format: json
    editor:
      preview: false
    fields:
      - {label: "Two-digit language code", name: "title", widget: "string"}
      - label: "Sidebar"
        name: "sidebar"
        widget: "object"
        fields: 
          - label: "Mailchimp boxes"
            name: "mailchimpBoxes"
            widget: "object"
            fields: 
              - label: "Subscribe"
                name: "subscribe"
                widget: "object"
                fields: 
                  - {label: "Heading", name: "heading", widget: "string"}
                  - {label: "Body", name: "body", widget: "string"}
                  - {label: "Button text", name: "buttonText", widget: "string"}
              - label: "Whitepaper"
                name: "whitepaper"
                widget: "object"
                fields: 
                  - {label: "Heading", name: "heading", widget: "string"}
                  - {label: "Body", name: "body", widget: "string"}
                  - {label: "Button text", name: "buttonText", widget: "string"}
          - label: "About"
            name: "about"
            widget: "object"
            fields: 
              - {label: "Heading", name: "heading", widget: "string"}
              - {label: "Body", name: "body", widget: "string"}
          - label: "Categories"
            name: "categories"
            widget: "object"
            fields: 
              - {label: "Heading", name: "heading", widget: "string"}
          - label: "Popular posts"
            name: "popularPosts"
            widget: "object"
            fields: 
              - {label: "Heading", name: "heading", widget: "string"}
          - label: "Social media"
            name: "socialMedia"
            widget: "object"
            fields: 
              - {label: "Heading", name: "heading", widget: "string"}
      - label: "Blog list"
        name: "blogList"
        widget: "object"
        fields: 
          - {label: "Read more link text", name: "readMoreLink", widget: "string"}


  - label: "Blog in French"
    name: "french_posts"
    folder: "content/posts"
    create: true
    filter: {field: "locale", value: "fr"}
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Language", name: "locale", widget: "select", options: ["fr", "en"], default: "fr"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "string", default: "fr-uncategorised"}
      - {label: "Tags", name: "tags", widget: "list", default: ["news"]}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Show on popular posts sidebar?", name: "isPopular", widget: "boolean"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Content", name: "body", widget: "markdown"}

  - label: "Blog in English"
    name: "english_posts"
    folder: "content/posts"
    create: true
    filter: {field: "locale", value: "en"}
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Language", name: "locale", widget: "select", options: ["fr", "en"], default: "en"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "string", default: "en-uncategorised"}
      - {label: "Tags", name: "tags", widget: "list", default: ["news"]}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Show on popular posts sidebar?", name: "isPopular", widget: "boolean"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Content", name: "body", widget: "markdown"}

