backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:

  - name: "authors"
    label: "Authors"
    folder: "content/authors"
    create: true
    extension: json
    format: json
    editor:
      preview: false
    fields:
      - {label: "Author ID", name: "title", widget: "string"}
      - {label: "Display name", name: "displayName", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}

  - name: "french_categories"
    label: "Categories in French"
    folder: "content/categories"
    filter: {field: "locale", value: "fr"}
    create: true
    extension: json
    format: json
    slug: "fr-{{slug}}"
    editor:
      preview: false
    fields:
      - {label: "Category ID", name: "title", widget: "string"}
      - {label: "Display name", name: "displayName", widget: "string"}
      - {label: "Locale", name: "locale", widget: "hidden", default: "fr"}
      - {label: "Colour (hex code)", name: "color", widget: "string"}

  - name: "english_categories"
    label: "Categories in English"
    folder: "content/categories"
    filter: {field: "locale", value: "en"}
    create: true
    extension: json
    format: json
    slug: "en-{{slug}}"
    editor:
      preview: false
    fields:
      - {label: "Category ID", name: "title", widget: "string"}
      - {label: "Display name", name: "displayName", widget: "string"}
      - {label: "Locale", name: "locale", widget: "hidden", default: "en"}
      - {label: "Colour (hex code)", name: "color", widget: "string"}

  - name: "languages"
    label: "Languages"
    folder: "data/translations"
    create: true
    extension: json
    format: json
    editor:
      preview: false
    fields:
      - {label: "Two-digit language code", name: "title", widget: "string"}
      - label: "Global"
        name: "global"
        widget: "object"
        fields: 
          - {label: "Languages label", name: "languagesLabel", widget: "string"}
          - label: "SEO"
            name: "seo"
            widget: "object"
            fields: 
              - {label: "Site title", name: "siteTitle", widget: "string"}
              - {label: "Site description", name: "siteDescription", widget: "string"}
              - {label: "Site keywords", name: "siteKeywords", widget: "string"}
      - label: "Navigation"
        name: "navigation"
        widget: "object"
        fields: 
          - {label: "Menu title", name: "menuTitle", widget: "string"}
          - {label: "Close button text", name: "closeButtonText", widget: "string"}
          - label: "Home"
            name: "home"
            widget: "object"
            fields: 
              - {label: "Link text", name: "linkText", widget: "string"}
              - {label: "Link URL", name: "linkUrl", widget: "string"}
          - label: "Offers"
            name: "offers"
            widget: "object"
            fields: 
              - {label: "Link text", name: "linkText", widget: "string"}
              - {label: "Link URL", name: "linkUrl", widget: "string"}
      - label: "Search"
        name: "search"
        widget: "object"
        fields: 
          - {label: "Search input label", name: "searchInputLabel", widget: "string"}
          - {label: "All categories label", name: "allCategoriesLabel", widget: "string"}
          - {label: "Search button text", name: "searchButtonText", widget: "string"}
          - {label: "No results label", name: "noResultsLabel", widget: "string"}
          - {label: "Search results label", name: "searchResultsLabel", widget: "string"}
          - {label: "Query prefix", name: "queryPrefix", widget: "string"}
          - {label: "Category prefix", name: "categoryPrefix", widget: "string"}
          - {label: "Empty query warning message", name: "emptyQueryWarning", widget: "string"}
      - label: "Sidebar"
        name: "sidebar"
        widget: "object"
        fields: 
          - label: "Mailchimp boxes"
            name: "mailchimpBoxes"
            widget: "object"
            fields: 
              - {label: "Email address label", name: "emailAddressLabel", widget: "string"}
              - {label: "Email address placeholder", name: "emailAddressPlaceholder", widget: "string"}
              - {label: "Success message", name: "successMessage", widget: "string"}
              - {label: "Invalid email message", name: "invalidEmailMessage", widget: "string"}
              - label: "Subscribe"
                name: "subscribe"
                widget: "object"
                fields: 
                  - {label: "Heading", name: "heading", widget: "string"}
                  - {label: "Body", name: "body", widget: "string"}
                  - {label: "Button text", name: "buttonText", widget: "string"}
              - label: "Whitepaper"
                name: "whitepaper"
                widget: "object"
                fields: 
                  - {label: "Heading", name: "heading", widget: "string"}
                  - {label: "Body", name: "body", widget: "string"}
                  - {label: "Button text", name: "buttonText", widget: "string"}
          - label: "About"
            name: "about"
            widget: "object"
            fields: 
              - {label: "Heading", name: "heading", widget: "string"}
              - {label: "Body", name: "body", widget: "string"}
          - label: "Categories"
            name: "categories"
            widget: "object"
            fields: 
              - {label: "Heading", name: "heading", widget: "string"}
          - label: "Popular posts"
            name: "popularPosts"
            widget: "object"
            fields: 
              - {label: "Heading", name: "heading", widget: "string"}
          - label: "Social media"
            name: "socialMedia"
            widget: "object"
            fields: 
              - {label: "Heading", name: "heading", widget: "string"}
      - label: "Blog list"
        name: "blogList"
        widget: "object"
        fields: 
          - {label: "Read more link text", name: "readMoreLink", widget: "string"}
      - label: "Post page"
        name: "post"
        widget: "object"
        fields: 
          - {label: "Tags heading", name: "tagsHeading", widget: "string"}
          - {label: "Author heading", name: "authorHeading", widget: "string"}
          - {label: "Related articles heading", name: "relatedArticlesHeading", widget: "string"}

  - label: "Blog in French"
    name: "french_posts"
    folder: "content/posts"
    create: true
    filter: {field: "locale", value: "fr"}
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Is published", name: "isPublished", widget: "boolean", default: true}
      - {label: "Language", name: "locale", widget: "hidden", default: "fr"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "relation", collection: "french_categories", searchFields: ["title", "displayName"], valueField: "title", displayFields: ["title", "displayName"]}
      - {label: "Tags", name: "tags", widget: "list", default: ["news"], required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "relation", collection: "authors", searchFields: ["title", "displayName"], valueField: "title", displayFields: ["displayName"]}
      - {
          label: "Alternate language links", 
          name: "alternateLangLinks", 
          widget: "list", 
          required: false,
          fields: [
            {
              label: "Language", 
              name: "language", 
              widget: "string"
            }, 
            {
              label: "Link URL", 
              name: "linkUrl", 
              widget: "string"
            }
          ]
        }
      - {label: "Show on popular posts sidebar?", name: "isPopular", widget: "boolean", required: false}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Content", name: "body", widget: "markdown"}
      - {
          label: "SEO", 
          name: "seo", 
          widget: "object", 
          required: false,
          fields: [
            {
              label: "Title", 
              name: "title", 
              required: false,
              widget: "string"
            },
            {
              label: "og:title", 
              name: "ogTitle", 
              required: false,
              widget: "string"
            },
            {
              label: "Description", 
              name: "description", 
              required: true,
              widget: "string"
            },
            {
              label: "og:description", 
              name: "ogDescription", 
              required: false,
              widget: "string"
            },
            {
              label: "Keywords", 
              name: "keywords", 
              widget: "list", 
              required: false
            },
            {
              label: "article:tag (comma-separated)", 
              name: "ogArticleTags", 
              widget: "list", 
              required: false
            },
            {
              label: "og:image", 
              name: "ogImage", 
              widget: "image", 
              required: false
            },
            {
              label: "Additional custom entries", 
              name: "additional", 
              widget: "list",
              required: false,
              fields: [
                {
                  label: "Type", 
                  name: "type", 
                  widget: "select",
                  options: ["name", "property"]
                }, 
                {
                  label: "Type value", 
                  name: "typeValue", 
                  widget: "string"
                }, 
                {
                  label: "Content", 
                  name: "content", 
                  widget: "string"
                }
              ]              
            }
          ]
        }

  - label: "Blog in English"
    name: "english_posts"
    folder: "content/posts"
    create: true
    filter: {field: "locale", value: "en"}
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Is published", name: "isPublished", widget: "boolean", default: true}
      - {label: "Language", name: "locale", widget: "hidden", default: "en"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "relation", collection: "english_categories", searchFields: ["title", "displayName"], valueField: "title", displayFields: ["title", "displayName"]}
      - {label: "Tags", name: "tags", widget: "list", default: ["news"], required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "relation", collection: "authors", searchFields: ["title", "displayName"], valueField: "title", displayFields: ["displayName"]}
      - {
          label: "Alternate language links", 
          name: "alternateLangLinks", 
          widget: "list", 
          required: false,
          fields: [
            {
              label: "Language", 
              name: "language", 
              widget: "string"
            }, 
            {
              label: "Link URL", 
              name: "linkUrl", 
              widget: "string"
            }
          ]
        }
      - {label: "Show on popular posts sidebar?", name: "isPopular", widget: "boolean", required: false}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Content", name: "body", widget: "markdown"}
      - {
          label: "SEO", 
          name: "seo", 
          widget: "object", 
          required: false,
          fields: [
            {
              label: "Title", 
              name: "title", 
              required: false,
              widget: "string"
            },
            {
              label: "og:title", 
              name: "ogTitle", 
              required: false,
              widget: "string"
            },
            {
              label: "Description", 
              name: "description", 
              required: true,
              widget: "string"
            },
            {
              label: "og:description", 
              name: "ogDescription", 
              required: false,
              widget: "string"
            },
            {
              label: "Keywords", 
              name: "keywords", 
              widget: "list", 
              required: false
            },
            {
              label: "article:tag (comma-separated)", 
              name: "ogArticleTags", 
              widget: "list", 
              required: false
            },
            {
              label: "og:image", 
              name: "ogImage", 
              widget: "image", 
              required: false
            },
            {
              label: "Additional custom entries", 
              name: "additional", 
              widget: "list",
              required: false,
              fields: [
                {
                  label: "Type", 
                  name: "type", 
                  widget: "select",
                  options: ["name", "property"]
                }, 
                {
                  label: "Type value", 
                  name: "typeValue", 
                  widget: "string"
                }, 
                {
                  label: "Content", 
                  name: "content", 
                  widget: "string"
                }
              ]              
            }
          ]
        }

